---
version: 1
enabled: true
comment_template_file: ".stoat/comment.hbs"
plugins:
  job_runtime:
    enabled: true
  json:
    ubuntu_issues:
      path: ubuntu-latest-issues.json
    windows_issues:
      path: windows-latest-issues.json
  static_hosting:
    coverage_image:
      path: coverage.svg
    coverage_html:
      path: coverage.html
    ubuntu_linter:
      path: ubuntu-latest-golangci.html
    windows_linter:
      path: windows-latest-golangci.html
    ubuntu_test_html:
      path: ubuntu-latest-junit.html
    windows_test_html:
      path: windows-latest-junit.html
