---
version: 1
enabled: true
comment_template_file: ".stoat/comment.hbs"
plugins:
  job_runtime:
    enabled: true
  json:
    issues:
      path: issues.json
  static_hosting:
    coverage_image:
      path: coverage.svg
    coverage_html:
      path: coverage.html
    test_html:
      path: junit.html
    linter:
      path: golangci.html
