name: E2E

#on:
#  push:
#    branches: [main]
#  pull_request:

jobs:
  install:
    name: E2E tests
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install CLI
        run: |
          go build -o ./inngest-bin ./cmd/main.go
          mv ./inngest-bin "$(go env GOPATH)/bin/inngest"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Run E2E tests
        run: make e2e

      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()

