name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1
          ./bin/golangci-lint run --verbose

      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test
        run: go test -coverprofile coverage.out -race ./...
      - name: Generate Coverage Treemap
        run: |
          go install github.com/nikolaydubina/go-cover-treemap@latest
          go-cover-treemap -h 240 -coverprofile coverage.out > coverage.svg
      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()
